server:
  port: 8082


spring:
  application:
    name: PhoneBook_Rest_App

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/phonebook
    username: root
    password: tanmoy
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
